version: 2.1

orbs:
  node: circleci/node@4.2.0
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: false
      - run: node --version
      - run: ls
      - run: cd src/app/ && ls
      - run: ls
workflows:
  test-my-app:
    jobs:
      - install-node-example
